# (PART) Fundamentos {-}

# Introdução {#fundamentos-introdução  .unnumbered}

Para iniciar sua jornada no domínio do R, os seis capítulos a seguir ajudarão a 
aprender os componentes fundamentais do R. 
Acreito que você já tenha visto muitas dessas peças antes, mas, provavelmente, 
não as estudou profundamente. Para ajudar a verificar o quanto você já sabe, 
cada capítulo começa com um questionário.
Se você acertar todas as perguntas, fique à vontade para pular para o próximo 
capítulo!

1.  O capítulo \@ref(names-values) ensina uma distinção importante sobre a qual 
    você provavelmente ainda não pensou profundamente: a diferença entre um 
    objeto e seu nome. Melhorar seu modelo mental ajudará a fazer melhores 
    previsões sobre quando o R copia dados e, portanto, quais operações básicas 
    são baratas e quais são caras.

1.  O capítulo \@ref(vectors-chap) mergulha nos detalhes dos vetores, ajudando 
    você a aprender como os diferentes tipos de vetores se encaixam. Você também 
    aprenderá sobre atributos, que permitem armazenar metadados arbitrários e 
    formam a base para dois dos kits de ferramentas de programação orientada a 
    objetos do R.

1.  O capítulo \@ref(subsetting) descreve como usar filtros para escrever 
    códigos em R de maneira clara, concisa e eficiente. A compreensão dos 
    componentes fundamentais permitirá que você resolva novos problemas 
    combinando os blocos de construção de maneiras novas. 

1.  O capítulo \@ref(control-flow) apresenta estruturas de controle de fluxo 
    que permitem executar apenas o código em determinadas condições ou executar 
    repetidamente o código com alterações nas entradas. Isso inclui as 
    importantes construções `if` e `for`, além de ferramentas relacionadas 
    como `switch()` e `while`.
    
1.  O capítulo \@ref(functions) trata de funções, os blocos de construção mais 
    importantes do código em R. Você aprenderá exatamente como elas funcionam, 
    incluindo as regras de escopo, que governam como o R pesquisa valores de 
    nomes. Você também aprenda mais sobre os detalhes por trás da avaliação 
    preguiçosa e como você pode controlar o que acontece quando 
    você sai de uma função.
    
1.  O capítulo \@ref(environments) descreve uma estrutura de dados que é crucial 
    para entender como o R funciona, mas que não é importante para a análise de 
    dados: o ambiente. Ambientes são a estrutura de dados que vincula nomes a 
    valores, e eles fornecem ferramentas importantes, como o espaço de nomes 
    (*namespace*) de um pacote. Diferentemente da maioria das linguagens de 
    programação, os ambientes em R são "de primeira classe", o que significa que 
    você pode manipulá-los como outros objetos.

1.  O capítulo \@ref(conditions) conclui os fundamentos do R com uma exploração 
    das "condições de exceção", o termo genérico usado para descrever erros, 
    avisos e mensagens. Você certamente já os encontrou antes, portanto, neste 
    capítulo, você aprenderá a sinalizá-los adequadamente em suas próprias 
    funções e como lidar com eles quando sinalizados em outro lugar.
