# Prefácio {-}

Bem-vindx à segunda edição de _R Avançado_. 
Eu tinha três objetivos principais para esta edição:

* Melhorar a abrangência de conceitos importantes que só compreendi 
completamente após a publicação da primeira edição.

* Reduzir a abrangência de tópicos que o tempo mostrou serem menos úteis, ou que 
acho realmente interessantes mas que não são tão práticos.

* Tornar, de forma geral, o material mais fácil de entender ao ter um texto 
melhor escrito, códigos mais claros e muito mais diagramas.

Se você estiver familiarizadx com a primeira edição, este prefácio descreve as 
principais mudanças para que você possa focar sua leitura nas novas áreas. Se 
você estiver lendo uma versão impressa deste livro (não disponível em Português 
- nota do tradutor), notará, prontamente, uma grande mudança: _R Avançado_ agora 
está em cores! Isso melhorou consideravelmente o destaque dado à sintaxe nos 
pedaços de código e facilitou muito a criação de diagramas mais didáticos. 
Tirei proveito disso e incluí mais de 100 novos diagramas ao longo do livro.

Outra grande mudança nesta versão é o uso de novos pacotes. Particularmente, 
o [rlang](http://rlang.r-lib.org), que fornece uma interface limpa para 
operações e estruturas de dados de baixo nível. A primeira edição usou, quase 
exclusivamente, funções básicas do R (chamadas de base-R), o que criou alguns 
desafios pedagógicos porque muitas funções evoluíram de forma independente com 
o passar dos anos. Isso dificultou a percepção de idéias fundamentais, que 
ficaram ocultas entre as variações incidentais nos nomes e nos argumentos das 
funções. Continuo mostrando os códigos equivalentes, escritos em base-R, nas 
barras laterais, notas de rodapé e, quando necessário, em seções individuais, 
mas se você quiser ver as idéias contidas neste livro expressas em base-R na 
sua forma mais pura, recomendo a leitura da primeira edição, disponível on-line 
em <http://adv-r.had.co.nz> (em inglês).

Os fundamentos do R não mudaram nos cinco anos desde a primeira edição, mas meu 
entendimento deles certamente mudou. Assim, a estrutura geral de "Fundamentos" 
permaneceu praticamente a mesma, mas muitos dos capítulos individuais foram 
aprimorados consideravelmente:

*   Capítulo \@ref(names-values), "Nomes e valores ", é um novo capítulo que 
    ajuda a entender a diferença entre objetos e nomes de objetos. Isso ajuda a 
    prever com mais precisão quando o R fará uma cópia de uma estrutura de dados 
    e estabelece conceitos importantes para entender a programação funcional.
    
*   Capítulo \@ref(vectors-chap), "Vetores" (anteriormente chamado de
    "Estruturas de dados"), foi reescrito para que o foco fique nos diferentes 
    tipos de vetores, como números inteiros, fatores e *data frames*. 
    Ele contém mais detalhes sobre importantes vetores de classe S3 (como datas 
    e data-hora), e discute a variante ao data frame oferecida
    pelo pacote tibble [@tibble] e, de forma geral, reflete minha melhor 
    compreensão dos tipos de dados em forma de vetores.

*   Capítulo \@ref(subsetting), "Filtros", agora distingue entre `[` e
    `[[` de acordo com seus propósitos: `[` extrai muitos valores e `[[` extrai 
    um valor único (anteriormente eles eram caracterizados como 
    "simplificadores" ou "preservadores"). A seção \@ref(subset-single) usa uma 
    "locomotiva" para te ajudar a entender como `[[` trabalha com listas e 
    apresenta novas funções que oferecem um comportamento mais consistente para 
    índices fora dos limites.

*   Capítulo \@ref(control-flow), "Estruturas de controle de fluxo", é um novo
    capítulo: de alguma forma, eu esqueci anteriormente sobre ferramentas importantes
    como o comando `if` e o laço de repetição `for`!

*   Capítulo \@ref(functions), "Funções", está melhor organizado,
    apresenta o pipe (`%>%`) como uma terceira maneira de compor funções (Seção
    \@ref(function-composition)) e tem uma abrangência consideravelmente melhor das 
    notações de funções (Seção \@ref(function-forms)).

*   Capítulo \@ref(environments), "Ambientes", possui uma nova organização da parte de
    ambientes especiais (Seção \@ref(special-environments)) e apresenta
    uma discussão melhorada sobre a pilha de chamadas (Seção \@ref(call-stack)).

*   Capítulo \@ref(conditions), "Condições de exceção", contém material anteriormente 
    em "Exceções e depuração" e muito conteúdo novo sobre como o sistema de tratamento 
    de exceção do R funciona. Também mostra como criar classes de exceção
    personalizadas (Seção \@ref(custom-conditions)).
    

Os capítulos após a Parte I, Fundamentos, foram reorganizados em torno dos três
paradigmas de programação mais importantes em R: programação funcional, programação
orientada a objetos e metaprogramação.


* Agora, a parte de programação funcional está melhor dividida em torno das três técnicas
  principais: "Funcionais" (Capítulo \@ref(functionals)), "Função Fábrica" (Capítulo
  \@ref(function-factories)) e "Funções de Alta Ordem" (Capítulo
  \@ref(function-operators)). Eu me concentrei em idéias que têm aplicações práticas
  em ciência de dados e reduzi a quantidade de teoria pura.
  
    Esses capítulos agora usam funções fornecidas pelo pacote purrr [@purrr], o que me
    permitiu focar mais nas idéias subjacentes e menos nos detalhes incidentais. Isso
    levou a uma simplificação considerável do capítulo sobre funções de alta ordem, uma
    vez que um objetivo importante era solucionar a ausência de elipses (`...`) nos
    funcionais do base-R.

* A programação orientada a objetos (POO, ou OOP segundo as suas siglas em inglês)
  agora forma uma seção importante do livro, com capítulos completamente novos sobre
  os tipos de objetos do base-R (Capítulo \@ref(base-types)), e dos sistemas
  S3 (Capítulo \@ref(s3)), S4 (Capítulo \@ref(s4)) e R6 (Capítulo \@ref(r6)), e os
  *trade-offs* entre os sistemas (Capítulo \@ref(oo-tradeoffs)). 
  
    Esses capítulos focam em como os diferentes sistemas de objetos funcionam, e não em
    como usá-los efetivamente. Isso é lamentável, mas necessário, porque muitos dos
    detalhes técnicos não são descritos em nenhum outro lugar, e o uso eficaz de OOP
    precisa de um livro inteiro só para isso.

* A metaprogramação (anteriormente chamada de "Computação na linguagem") descreve o
  conjunto de ferramentas que você pode usar para gerar código com código. Comparado à
  primeira edição, este material foi expandido e agora se concentra na "avaliação
  organizada" (em inglês, "tidy evaluation"), que é um conjunto de idéias e teoria que
  tornam a metaprogramação segura, bem fundamentada e acessível a muitos mais
  programadores de R.  O capítulo \@ref(meta-big-picture), "Quadro Geral", descreve 
  de maneira grosseira como todas as peças se encaixam; o capítulo \@ref(expressions),
  "Expressões", descreve as estruturas de dados subjacentes; o capítulo 
  \@ref(quasiquotation), "Quasiquotation", abrange métodos para avaliar argumentos que
  contêm e não contêm aspas; o capítulo \@ref(evaluation), "Avaliação", explica o
  método de avaliação do código em ambientes especiais; e o capítulo \@ref(translation),
  "Traduções", reúne todos os temas para mostrar como você pode traduzir de um idioma 
  (de programação) para outro.
  
A seção final do livro reúne os capítulos sobre técnicas de programação: criação de
perfil (profiling), medição e melhoria de desempenho, e Rcpp (integração entre R e C ++).
O conteúdo é muito parecido com o da primeira edição, embora a organização seja um pouco
diferente. Fiz atualizações leves ao longo desses capítulos, especialmente para usar
pacotes mais recentes (microbenchmark -> bench, lineprof -> profvis), mas a maioria do
texto é a mesma.

Enquanto a segunda edição expandiu principalmente a abrangência do material existente,
cinco capítulos foram removidos:

* O capítulo de vocabulário foi removido porque sempre foi um pouco estranho, e existem 
  maneiras mais eficazes de apresentar listas de vocabulário do que em um capítulo de
  livro.

* O capítulo de estilo foi substituído por um guia de estilo on-line (em 
  inglês), <http://style.tidyverse.org/>. O guia de estilo está pareado com o 
  novo pacote de estilos chamado styler [@styler], que pode aplicar 
  automaticamente muitas das regras.

* O capítulo sobre C foi movido para <https://github.com/hadley/r-internals>, 
  que, com o tempo, fornecerá um guia para escrever código em C que funcione 
  com as estruturas de dados do R.

* O capítulo de gerenciamento de memória foi removido. Grande parte do material 
  foi integrada ao Capítulo \@ref(names-values) e o restante parecia 
  excessivamente técnico e não tão importante.

* O capítulo sobre o desempenho do R como linguagem foi removido. Ele forneceu 
  poucos *insights* práticos e ficou datado quando o R mudou.
